version: "3.8"
services:
  db:
    image: postgres:15.2
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: nest-graphql-starter-db

volumes:
  data:
